//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMst
    {
        public int CU_Id { get; set; }
        public string CU_Name { get; set; }
        public string CU_Surname { get; set; }
        public Nullable<double> CU_Mobile_No { get; set; }
        public string CU_Address { get; set; }
        public string CU_City { get; set; }
    }
}
