//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMst
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public string Person { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
