//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalContext : DbContext
    {
        public MedicalContext()
            : base("name=MedicalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientMst> ClientMsts { get; set; }
        public virtual DbSet<CompanyMst> CompanyMsts { get; set; }
        public virtual DbSet<SalesMst> SalesMsts { get; set; }
        public virtual DbSet<StockInMst> StockInMsts { get; set; }
        public virtual DbSet<StockMst> StockMsts { get; set; }
        public virtual DbSet<StockOutMst> StockOutMsts { get; set; }
        public virtual DbSet<UserMst> UserMsts { get; set; }
    }
}
