//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutMst
    {
        public int S_Id { get; set; }
        public string C_Name { get; set; }
        public string I_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
    }
}
