//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInMst
    {
        public int I_Id { get; set; }
        public string I_Name { get; set; }
        public string I_Descrip { get; set; }
        public Nullable<int> I_Quantity { get; set; }
        public Nullable<double> I_Price { get; set; }
        public string C_Name { get; set; }
        public Nullable<System.DateTime> I_Ex_Date { get; set; }
        public string I_Location { get; set; }
    }
}
