//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMst
    {
        public int S_Id { get; set; }
        public string IName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> SellQuantity { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> AvaiablePrice { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
    }
}
