//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Store_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMst
    {
        public int U_Id { get; set; }
        public string U_Name { get; set; }
        public string U_Password { get; set; }
        public string U_Type { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
    }
}
